import assert from "node:assert/strict";
import {stageConsensus} from "../src/data/tuning-profiles/consensus.ts";
import {applyLargeGainScrutiny,negativeSourceConflicts,sourceIsAvailable} from "./tuning-source-evidence.ts";
import type {SourceObservation} from "../src/data/tuning-profiles/schema.ts";
const source:SourceObservation={id:"atm-positive",provider:"atm-chiptuning",sourceName:"ATM",url:"https://example.test/t6",retrievedAt:"2026-09-16T00:00:00Z",status:"retrieved",retrievalMethod:"page",contentSha256:"a".repeat(64),identity:{brand:"Volkswagen",modelFamily:"Transporter",generation:"T6",yearFrom:2015,yearTo:2019,fuel:"Diesel",displacementCc:1968,displacementPrecision:"exact",engineMarketingName:"2.0 TDI",stockPowerHp:150,stockTorqueNm:340,powerUnit:"PS",torqueUnit:"Nm"},stages:{stage1:{powerHp:190,torqueNm:410}}};
const negative:SourceObservation={...source,id:"atm-negative",url:"https://example.test/t61",identity:{...source.identity!,generation:"T6.1",yearFrom:2021,yearTo:2024},availability:{status:"development-pending",scope:"source-application-only",evidence:"Synthetic application unavailable"}};
assert.equal(sourceIsAvailable(negative),false);
assert.equal(stageConsensus([negative],"stage1"),undefined,"Negative source never votes even with stale numeric markup");
assert.deepEqual(negativeSourceConflicts(source,[negative]),[],"Earlier generation stays usable");
const leaked={...source,identity:{...source.identity!,yearTo:2024}};
assert.deepEqual(negativeSourceConflicts(leaked,[negative]),[negative.id],"Old source cannot bleed into the unavailable generation");
assert.deepEqual(negativeSourceConflicts({...leaked,provider:"shiftech"},[negative]),[],"A provider-specific negative is not global unsupported");
assert.deepEqual(negativeSourceConflicts({...leaked,reviewedScope:{yearFrom:2015,yearTo:2019,sourceUrl:negative.url,retrievedAt:negative.retrievedAt,contentSha256:negative.contentSha256!,reason:"Explicit predecessor scope"}},[negative]),[],"Reviewed narrowing resolves overlap");
assert.deepEqual(negativeSourceConflicts(leaked,[{...negative,retrievalMethod:"search-index"}]),[],"Search-index statements cannot veto actual facts");
assert.deepEqual(negativeSourceConflicts({...leaked,identity:{...leaked.identity!,stockPowerHp:102}},[negative]),[],"Output-specific negative");
assert.deepEqual(negativeSourceConflicts({...leaked,identity:{...leaked.identity!,displacementCc:1498}},[negative]),[],"Displacement-specific negative");
assert.deepEqual(negativeSourceConflicts({...leaked,identity:{...leaked.identity!,modelFamily:"Caddy"}},[negative]),[],"No sibling-model negative bleed");
const large={...source,identity:{...source.identity!,stockPowerHp:100,stockTorqueNm:250}};
const second={...large,id:"second",provider:"shiftech" as const,stages:{stage1:{powerHp:185,torqueNm:400}}};
const single=stageConsensus([large],"stage1")!;
assert.deepEqual(applyLargeGainScrutiny([large],single,false),{largeGain:true,extraEvidenceSatisfied:false});
assert.equal(single.ownerReviewRequired,true);
assert.ok(single.conditions.includes("LARGE_GAIN_REQUIRES_EXTRA_EVIDENCE"));
const pair=stageConsensus([large,second],"stage1")!;
assert.deepEqual(applyLargeGainScrutiny([large,second],pair,false),{largeGain:true,extraEvidenceSatisfied:true});
assert.ok(pair.selectedPowerHp<=190&&pair.selectedPowerHp>=185,"Conservative provider consensus");
const conflict=stageConsensus([large,{...second,stages:{stage1:{powerHp:250,torqueNm:500}}}],"stage1")!;
assert.equal(applyLargeGainScrutiny([large,second],conflict,false).extraEvidenceSatisfied,false);
assert.equal(conflict.ownerReviewRequired,true);
const mirror=stageConsensus([large,{...second,provider:"atm-chiptuning"}],"stage1")!;
assert.equal(applyLargeGainScrutiny([large,second],mirror,false).extraEvidenceSatisfied,false,"Same-provider mirrors are not independent");
assert.equal(applyLargeGainScrutiny([large],stageConsensus([large],"stage1")!,true).extraEvidenceSatisfied,true,"Explicit validated factory evidence alternative");
const boundary={...large,stages:{stage1:{powerHp:145,torqueNm:360}}};
assert.equal(applyLargeGainScrutiny([boundary],stageConsensus([boundary],"stage1")!,false).largeGain,false,"Exactly 45 percent is not above the threshold");
const torqueOnly={...source,stages:{stage1:{powerHp:190,torqueNm:510}}};
assert.equal(applyLargeGainScrutiny([torqueOnly],stageConsensus([torqueOnly],"stage1")!,false).largeGain,true,"Torque-only large gain checked");
assert.equal(stageConsensus([{...source,packages:[{name:"External",kind:"external-module"}]}],"stage1"),undefined,"Modules never become votes");
console.log("Source evidence: 22 negative-generation, independent-vote and large-gain assertions passed.");
